#!/bin/bash

# Text Styles
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
TEXT_NORMAL=$ESC_SEQ"0m"

TEXT_BLINK=$ESC_SEQ"5m"
TEXT_BLINK_RESET=$ESC_SEQ"25m"

TEXT_HIDDEN=$ESC_SEQ"8m"
TEXT_HIDDEN_RESET=$ESC_SEQ"28m"

TEXT_COLOR_INVERSE=$ESC_SEQ"7m"
TEXT_INVERSE_RESET=$ESC_SEQ"27m"

TEXT_BOLD=$ESC_SEQ"1m"
TEXT_BOLD_RESET=$ESC_SEQ"22m"
TEXT_BOLD_OFF=$ESC_SEQ"21m"

TEXT_UNDERLINE=$ESC_SEQ"4m"
TEXT_UNDERLINE_RESET=$ESC_SEQ"24m"


# Foreground/Text Colors
COL_RED=$ESC_SEQ"31;01m"
COL_RED_LITE=$ESC_SEQ"91;01m"

COL_GREEN=$ESC_SEQ"32;01m"
COL_GREEN_LITE=$ESC_SEQ"92;01m"

COL_YELLOW=$ESC_SEQ"33;01m"
COL_YELLOW_LITE=$ESC_SEQ"93;01m"

COL_BLUE=$ESC_SEQ"34;01m"
COL_BLUE_LITE=$ESC_SEQ"94;01m"

COL_MAGENTA=$ESC_SEQ"35;01m"
COL_MAGENTA_LITE=$ESC_SEQ"95;01m"

COL_CYAN=$ESC_SEQ"36;01m"
COL_CYAN_LITE=$ESC_SEQ"96;01m"

COL_GRAY=$ESC_SEQ"90;01m"
COL_GRAY_LITE=$ESC_SEQ"37;01m"

COL_WHITE=$ESC_SEQ"97;01m"



### Examples
# echo -e $COL_RED"This is red text"$COL_RESET

# echo -e $TEXT_BOLD"This is bold text"$TEXT_BOLD_OFF 

# echo -e $TEXT_UNDERLINE $COL_GREEN"This is underlined green text"$TEXT_NORMAL

# echo -e but is this