---
version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - TZ=Europe/London
      - DOCKER_HUB_USERNAME=USER #optional
      - DOCKER_HUB_PASSWORD=PASS #optional
    volumes:
      - /path/to/data:/opt
      - /path/to/profiles:/profiles #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
