#!/usr/bin/env bash

# Add color
## ANSI_RED=$'\033[1;31m'
declare -r -x RED=$'\033[1;31m'
declare -r -x RED_LITE=$'\033[1;91m'
declare -r -x LRED="$RED_LITE"

## ANSI_YEL=$'\033[1;33m' && YEL="$ANSI_YEL"
declare -r -x YEL=$'\033[1;33m'
declare -r -x YELLOW="$YEL"
declare -r -x YEL_LITE=$'\033[1;93m'
declare -r -x LYEL="$YEL_LITE"

#ANSI_GRN=$'\033[1;32m' && GRN="$ANSI_GRN"
declare -r -x GRN=$'\033[1;32m'
declare -r -x GREEN="$GRN"
declare -r -x GRN_LITE=$'\033[1;92m'
declare -r -x LGRN="$GRN_LITE"

## ANSI_GRN=$'\033[0;32m' && GRN="$ANSI_GRN"
declare -r -x GRN2=$'\033[0;32m'
declare -r -x GREEN2="$GRN2"
declare -r -x GRN2_LITE=$'\033[0;92m'
declare -r -x LGRN2="$GRN2_LITE"

## ANSI_PRPL=$'\033[1;35m' && PRPL="$ANSI_PRPL"
declare -r -x PRPL=$'\033[1;35m'
declare -r -x PURPLE="$PRPL"
declare -r -x PRPL_LITE=$'\033[1;95m'
declare -r -x LPRPL="$PRPL_LITE"

## ANSI_VIO=$'\033[1;35m' && VIO="$ANSI_VIO"
declare -r -x VIO=$'\033[1;35m'
declare -r -x VIOLET="$VIO"
declare -r -x VIO_LITE=$'\033[1;95m'
declare -r -x LVIO="$VIO_LITE"

## ANSI_CYN=$'\033[1;36m' && CYN="$ANSI_CYN"
declare -r -x CYN=$'\033[1;36m'
declare -r -x CYAN="$CYN"
declare -r -x CYN_LITE=$'\033[1;96m'
declare -r -x LCYN="$CYN_LITE"

## ANSI_BLU=$'\033[1;34m' && BLU="$ANSI_BLU"
declare -r -x BLU=$'\033[1;34m'
declare -r -x BLUE="$BLU"
declare -r -x BLU_LITE=$'\033[1;94m'
declare -r -x LBLU="$BLU_LITE"

## ANSI_BRN=$'\033[0;33m' && BRN="$ANSI_BRN"
declare -r -x BRN=$'\033[0;33m'
declare -r -x BROWN="$BRN"
declare -r -x BRN_LITE=$'\033[0;93m'
declare -r -x LBRN="$BRN_LITE"

## ANSI_PNK=$'\033[0;35m' && PNK="$ANSI_PNK"
declare -r -x PNK=$'\033[0;35m'
declare -r -x PINK="$PNK"
declare -r -x PNK_LITE=$'\033[0;95m'
declare -r -x LPNK=$'\033[0;95m'

## ANSI_LGRY=$'\033[0;37m' && LGRY="$ANSI_LGRY"
## AMSO_GRY=$'\033[0;37m' && GRY="$AMSO_GRY"
declare -r -x GRY=$'\033[0;37m'
declare -r -x GRAY="$GRY"
declare -r -x GRY_LITE=$'\033[0;97m'
declare -r -x LGRY="$GRY_LITE"
declare -r -x GRY_LITE2=$'\033[0;90m'
declare -r -x LGRY2="$GRY_LITE2"
declare -r -x GRY_LITE3=$'\033[0;37m'
declare -r -x LGRY3="$GRY_LITE3"

## ANSI_DGRY=$'\033[1;30m' && DGRY="$ANSI_DGRY"
declare -r -x DGRY=$'\033[1;30m'
declare -r -x DGRAY="$DGRY"
declare -r -x DGRY_LITE=$'\033[1;90m'
declare -r -x LDGRY="$DGRY_LITE"

## ANSI_BLK=$'\033[0;30m' && BLK="$ANSI_BLK"
declare -r -x BLK=$'\033[0;30m'
declare -r -x BLACK="$BLK"

## ANSI_WHT=$'\033[1;37m' && WHT="$ANSI_WHT"
declare -r -x WHT=$'\033[1;37m'
declare -r -x WHITE="$WHT"

######
## ANSI_NORMAL=$'\033[0m' && NORMAL="$ANSI_NORMAL"
declare -r -x NORMAL=$'\033[0m'

## BOLD=$'\033[1m' && BLD="$BOLD"
declare -r -x BLD=$'\033[1m'
declare -r -x BOLD="$BLD"
declare -r -x BLDOFF=$'\033[21m'
declare -r -x BOLD_OFF="$BLDOFF"
declare -r -x BLD_RST=$'\033[22m'
declare -r -x BOLD_RESET="$BLD_RST"

## ANSI_UL=$'\033[4m' && UL="$ANSI_UL"
declare -r -x UL=$'\033[4m'
declare -r -x UNDERLINE="$UL"
declare -r -x UL_OFF=$'\033[24m'
declare -r -x UNDERLINE_OFF="$UL_OFF"


## ANSI_REV=$'\033[7m' && REV="$ANSI_REV"
declare -r -x REV=$'\033[7m'
declare -r -x REVERSE="$REV"
declare -r -x REV_RST=$'\033[27m'
declare -r -x REVERSE_RESET="$REV_RST"


## ANSI_DIM=$'\033[2m' && DIM="$ANSI_DIM"
declare -r -x DIM=$'\033[2m'
declare -r -x DIM_RST=$'\033[22m'


## ANSI_BLINK=$'\033[5m' && BLINK="$ANSI_BLINK"
declare -r -x BLINK=$'\033[5m'
declare -r -x BLINK_SLOW=$'\033[5;5m'
declare -r -x BLINK_RAPID=$'\033[5;6m'
declare -r -x BLINK_RST=$'\033[5;25m'

## ANSI_INV=$'\033[7m' && INV="$ANSI_INV"
declare -r -x INV=$'\033[7m'
declare -r -x INV_RST=$'\033[27m'

## ANSI_HID=$'\033[8m' && HID="$ANSI_HID"
declare -r -x HID=$'\033[8m'
declare -r -x HID_RST=$'\033[28m'

## ANSI_STRIKE=$'\033[9m' && STRIKE="$ANSI_STRIKE"
declare -r -x STRIKE=$'\033[9m'
declare -r -x STRIKE_RST=$'\033[29m'

## ANSI_STANDOUT=$'\033[3m' && STANDOUT="$ANSI_STANDOUT"
declare -r -x STDOUT=$'\033[3m'
declare -r -x STANDOUT="$STDOUT"
declare -r -x STDOUT_RST=$'\033[23m'
declare -r -x STANDOUT_RESET="$STDOUT_RST"

## ANSI_RST=$'\033[0m' && RST="$ANSI_RST"
declare -r -x RST=$'\033[0m'
declare -r -x RESET=$'\033[0m'


print_color() {
  printf "%b%s%b\n" "$2" "$1" "$RST"
}